Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -3,37 +3,57 @@ name: hacko-backend-go production deployment
 on:
   push:
     branches:
-      - main 
+      - main
 
 jobs:
   build:
     runs-on: ubuntu-latest
-    
+  
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
+      with:
+        fetch-depth: 1
+  
     - name: Login to Docker Hub
-      uses: ./
+      uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
-    - name: Build Docker image
+  
+    - name: Build and Push Docker image with cache
+      env:
+        DOCKER_BUILDKIT: 1
       run: |
-        docker build -t mortomulu/hacko:latest .
-    - name: Push Docker image
-      run: |
-        docker push mortomulu/hacko:latest
-    
+        docker pull mortomulu/hacko:latest || true
+        docker buildx build \
+          --platform linux/amd64 \
+          --cache-from=mortomulu/hacko:latest \
+          --cache-to=type=inline \
+          -t mortomulu/hacko:latest \
+          --push .
+          
   deploy:
     runs-on: ubuntu-latest
-    needs: build  
-    
+    needs: build
+
     steps:
     - name: Set up SSH
       uses: webfactory/ssh-agent@v0.5.3
       with:
-        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 
+        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-    - name: Pull Docker image and run Docker Compose on VPS
+    - name: Pull Docker image and restart container
       run: |
-        ssh -o StrictHostKeyChecking=no user@vps-ip "cd /hacko && docker-compose pull && docker-compose up -d"
+        ssh -o StrictHostKeyChecking=no user@vps-ip <<EOF
+            cd /hacko
+            echo "Pulling latest image..."
+            docker pull mortomulu/hacko:latest || { echo "Failed to pull image"; exit 1; }
+            echo "Stopping and removing old container..."
+            docker stop hacko-container || true
+            docker rm hacko-container || true
+            echo "Starting new container..."
+            docker run --env-file .env -d --restart unless-stopped --name hacko-container mortomulu/hacko:latest || { echo "Failed to start container"; exit 1; }
+            echo "Pruning unused images..."
+            docker image prune -f
+        EOF
